# Site settings

title: Simulando
tagline: "Um fã-site de The Sims e SimCity"
email: contato@simulando.net
description: >-
  Notícias, guias e discussões sobre The Sims e SimCity.

logo: "/assets/images/logo.png"
lang: pt-BR
timezone: "America/Sao_Paulo"

# Build settings
url: "https://simulando.net"
baseurl: ""

theme: steve-for-jekyll

steve:
  archives: # Prefixes used with archive titles
    date: Posts de
    tag: Mais posts sobre…
    category: Posts arquivados em
  date_formats: # Uses <http://strftime.net>
    post: "%d/%m/%Y" # The date format used in the post layout.
    archives: # The date formats for the archive layout.
      day: "%d/%m/%Y"
      month: "%m/%Y"
      year: "%Y"
  page_404: |+
    A página que você está procurando não foi encontrada. Talvez a busca possa te ajudar.
  pagination: # Strings used in the blog- and post-pagination.
    next_page: "&laquo; Posts mais recentes"
    prev_page: "Posts anteriores &raquo;"
    prev_post: "Anterior:"
    next_post: "Próximo:"
  post: # Strings used in the post layout.
    byline: "Por"
    tags: Mais sobre…
  search: # Strings used in the search form.
    label: Pesquisar
    placeholder: O que você está procurando?
    submit: Vai!

comments:
  title: Comentários
  form_title: Comentar
  date_format: "%d/%m/%Y às %k:%M"
  staticman_endpoint: "https://esporobot.herokuapp.com/v3/entry/github/esporo/simulando/main/comments"
  notice: |+ # Accepts Markdown
    Comentários são moderados, então o seu comentário pode demorar um pouco para aparecer no site.
  fields:
    name:
      label: Nome
      placeholder: "Seu nome"
    email:
      label: Endereço de email
      placeholder: "seu@email.net"
    website:
      label: Site ou blog
      placeholder: "https://seu-link.com/"
    message:
      label: Mensagem
      placeholder: Seu comentário
    submit: Enviar comentário

permalink: "/:year/:month/:title/"

keep_files:
  - apple-touch-icon.png
  - favicon.png
  - favicon.ico
  - uploads
  - assets

# Plugin: jekyll-paginate
paginate: 5
paginate_path: "/pagina/:num/"
seo_paginator_message: "Página %<current>s de %<total>s / "

# Plugin: jekyll-seo-tag
twitter:
  card: summary
  username: simulandonet

social:
  name: Simulando
  links:
    - https://twitter.com/simulandonet
    - https://www.facebook.com/simulandonet

# Plugin: jekyll-archives
jekyll-archives:
  enabled: all
  layout: "archive"
  slug_mode: default
  permalinks:
    category: "/:name/"
    tag: "/tags/:name/"
    year: "/:year/"
    month: "/:year/:month/"
